export const essentials = [
  "https://www.youtube.com/watch?v=DYHng61lftA&ab_channel=CarreroQuirogaDanielAlejandro",
  "https://www.youtube.com/watch?v=6TWdLqER014&ab_channel=WalterCalloni",
  "https://www.youtube.com/watch?v=cJunCsrhJjg&ab_channel=JimiHendrixVEVO",
  "https://www.youtube.com/watch?v=NWJwj4tZMOU&ab_channel=PaulRatcliff",
  "https://www.youtube.com/watch?v=3c_8VUL5jks&ab_channel=stevierayvaughnVEVO",
  "https://www.youtube.com/watch?v=VSLc0tCnOrM&ab_channel=stevie%27sblues",
  "https://www.youtube.com/watch?v=hHHY3eRUMsM&ab_channel=feedbackbro",
  "https://www.youtube.com/watch?v=AU432SxopNM&ab_channel=HoraceWinkk",
  "https://www.youtube.com/watch?v=PDLFoKwTtk4&ab_channel=belinleelo",
  "https://www.youtube.com/watch?v=WZn9QZykx10&ab_channel=neilyoungchannel",
  "https://www.youtube.com/watch?v=OuVIJlSDOs0&ab_channel=neilyoungchannel",
  "https://www.youtube.com/watch?v=pKwQlm-wldA&ab_channel=EricClaptonVEVO",
  "https://www.youtube.com/watch?v=P701paKEMXs&ab_channel=EchelonEntertainment",
  "https://www.youtube.com/watch?v=fJlkkRub6MU&ab_channel=Hayato0313",
  "https://www.youtube.com/watch?v=ZPwCnNwhgFA&ab_channel=johnmayerVEVO",
  "https://www.youtube.com/watch?v=yVrMqvu2_fE&ab_channel=tavarinho123",
];
